spring:
  datasource:
    url: jdbc:mysql://localhost:3307/onion-db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: onion-user
    password: onion1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

elasticsearch:
  host: localhost

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
  info:
    title: My API Documentation
    description: API documentation for my application
    version: 1.0.0

jwt:
  secret: secretKeyImAmDeveloper
  valid-time:
    access: 6000000
    refresh: 36000000

